language: rust
cache: cargo
sudo: required
services:
- docker
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libpcap0.8-dev
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
after_success:
- test $TRAVIS_RUST_VERSION = stable && docker create --name builder woutifier/rust-musl-builder /bin/bash -c "sudo chown -R rust:rust /home/rust/src; cargo build --release --verbose" && docker cp "${TRAVIS_BUILD_DIR}/." builder:/home/rust/src && docker start -i builder && docker cp builder:/home/rust/src/target/x86_64-unknown-linux-musl/release/pinger $TRAVIS_BUILD_DIR/pinger
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Ffc4Pz2QWhTTsBprwU8qP6gC9hldNa6IkAq3huZ0pDsr3ssYSJQ+CPAyGcGSiDDkTuGC/5BqW2AcP4SuCSxQUZVcKsftm2aF/bRSjuYB4OOfpf/sbbB8NYnkZMDqXFCLqDsurgDuW/hmWASVrEzbC/Fcl3WfTk42vuv3vFJJ8TIEWIXBC7g5xMGZOt4wY4TLtTmEcTwXklrMtx9EG0OrgTaded03AS9TNE14mqv02K1ImgCjU6LdkJ/oE6CKo42pquR+q3hUdtYwc3j1IoE2/zNodJqnQ9IgdXOhzu2UI/kGj5C3tioDXXHty1KhKSjn8kG9itAHk56QxO0RCsiLSstUgpkKN0ljyPFNsK1ImsFDYBNQ7rErpgPAGevWWLUuUZHwqiN/tGkoTyPS1oxVpCNKRw/OKUiLqhNhjzSOiXmhYvLtOZnqFMz093CkUS70GaB8jqHfBtD5MZk2FJhADqkS4BNohEtKn9bMvf7U+B8z9YlNoB69OCkKX2WH4gztOyDhkTZCCqMvHbxVK61mlge/a9TEF58fNip861mwWO3G5fBMdcXRHlcQjKCbPmLY6Lju3u3Wl8zvUobRmm7dGhC+EAV1ocpa0I+SNGPW4LrBNLd+GYpfRuZ3TO2uPU9OIV6tQLJtoZNaMf9Qh511Vktfq6esW8jXYdOkeXowbyY=
  file: $TRAVIS_BUILD_DIR/pinger
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    repo: Woutifier/pinger
    tags: true
